name: "Automatic building"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["gulpfile.js", "source/**", "static/**"]

jobs:
  build-all:
    strategy:
      matrix:
        build-type: ["dev", "site"]
    name: "Build all"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
    - name: "Setup Node.js"
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: "package-lock.json"
    - run: >
        npm ci
    - name: "Build ${{matrix.build-type}}"
      run: >
        npm exec gulp build-${{matrix.build-type}}
    - name: "Upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: "build-${{matrix.build-type}}"
        path: "build/"
